language: node_js
cache: yarn
node_js:
  - "9.3.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn
  - yarn deploy:release
after_success:
 - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then npm run deploy; rc=$?; elif [[ "$TRAVIS_BRANCH" == "release" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then npm run deploy:release; rc=$?; fi; exit $rc;
