image: node:9.3.0
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - curl -o- -L https://yarnpkg.com/install.sh | bash
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn
            - yarn deploy:release
